# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataform', '0002_auto_20171111_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='topmenu',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='submenumodel',
            old_name='topmenu',
            new_name='menu',
        ),
    ]
